### ISSUE TITLE
PanZoom not working

### ISSUE THREAD

**Issue by Strap1** [LGLabGreg/LGMap#2]
Hi there. Cheers for these nice maps and project.

Small issue: I can't see why the panzoom functionality is not working.

[My project](http://dev.j-moore.uk/europe/)

Init code:

```
$('#europeanUnion-map').LGMap({
        map: 'europeanUnion',
        enablePanZoom: true,
        mapWidth: 666.000,
        mapHeight: 658.700,
        responsive: true,
        offColor: '#ccc',
        strokeColor: '#24221f',
        useTextAtBottom: false,
        defaultText: "<h1>Blah blah.</h1>"
    });
```

Would you also mind tagging releases here? It makes it easier to track changes.

Thanks

**Comment by LGLabGreg** [comment]
Hi,

There was a bug when the map had no pins, use the latest js file: https://github.com/LGLabGreg/LGMap/blob/master/src/lg-map/lg-map.js

**Comment by Strap1** [comment]
Thanks for that. Panzoom working now.
